const $ = (id) => document.getElementById(id);
const storeKey = 'money-journal-data-v1';
const categories = { expense: [['食費','🍚'],['日用品','🧺'],['交通','🚃'],['趣味','🎨'],['交際','☕'],['固定費','🏠'],['医療','💊'],['その他','⋯']], income: [['給与','💼'],['副収入','✨'],['おこづかい','🎁'],['その他','⋯']] };
let filter = 'all'; let selectedType = 'expense';
let data = load();
function applyTheme(){ document.body.dataset.theme=data.theme||'blue'; document.querySelectorAll('.theme-choice').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===document.body.dataset.theme)); }
const themePicker=document.createElement('div'); themePicker.className='theme-picker'; themePicker.innerHTML='<p>アクセントカラー</p><div class="theme-options"><button class="theme-choice" data-theme-choice="blue" aria-label="ブルー"></button><button class="theme-choice" data-theme-choice="green" aria-label="グリーン"></button><button class="theme-choice" data-theme-choice="purple" aria-label="パープル"></button><button class="theme-choice" data-theme-choice="orange" aria-label="オレンジ"></button></div>'; $('settingsDialog').querySelector('.settings-note').after(themePicker); themePicker.onclick=e=>{const choice=e.target.closest('.theme-choice');if(!choice)return;data.theme=choice.dataset.themeChoice;persist();applyTheme();}; applyTheme();
document.querySelectorAll('.close').forEach(button=>button.onclick=()=>button.closest('dialog').close());

function load(){ const initial={transactions:[],goals:[],goal:{name:'貯金目標',target:0,saved:0,deadline:''},budget:0,assets:{total:0,asOf:'',startDate:''},categories:{expense:[],income:[]}}; try { const saved=JSON.parse(localStorage.getItem(storeKey)); if(!saved) return initial; const raw=Array.isArray(saved.goals)?saved.goals:(saved.goal?.target?[{id:'legacy-goal',type:'save',name:saved.goal.name||'貯金目標',target:saved.goal.target,startDate:dateValue(),deadline:saved.goal.deadline||''}]:[]); const goals=raw.map(g=>({...g,type:g.type==='purchase'?'save':g.type,initialAmount:Number(g.initialAmount)||0,priority:g.priority||'normal'})); return {...initial,...saved,goals,assets:{...initial.assets,...saved.assets},categories:{...initial.categories,...saved.categories}}; } catch { return initial; } }
function persist(){ localStorage.setItem(storeKey, JSON.stringify(data)); }
function yen(value){ return new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(value); }
function dateValue(date = new Date()){ const offset=date.getTimezoneOffset()*60000; return new Date(date-offset).toISOString().slice(0,10); }
function monthValue(date = new Date()){ return dateValue(date).slice(0,7); }
function currentMonth(){ return $('monthInput').value || monthValue(); }
function formatMonth(month){ const [year, m] = month.split('-'); return `${year}年${Number(m)}月`; }
function allCategories(type){ return [...categories[type].map(([name])=>name), ...(data.categories[type]||[])]; }
function categoryOptions(type, selected=''){ const names=allCategories(type); if(selected && !names.includes(selected)) names.push(selected); $('category').innerHTML=names.map(name=>`<option value="${escapeHtml(name)}" ${name===selected?'selected':''}>${escapeHtml(name)}</option>`).join('')+'<option value="__new__">＋ 新しいカテゴリを追加</option>'; toggleNewCategory(); }
function iconFor(category){ return Object.values(categories).flat().find(([name])=>name===category)?.[1] || '◌'; }
function netOf(items){ return items.reduce((sum,t)=>sum+(t.type==='income'?t.amount:-t.amount),0); }
const priorityLabels={highest:'最優先',high:'高',normal:'通常',low:'低'}; const priorityOrder={highest:0,high:1,normal:2,low:3};
function goalProgress(goal){ const related=data.transactions.filter(t=>t.date>=goal.startDate&&(!goal.deadline||t.date<=goal.deadline)); if(goal.type==='restore'&&goal.sourceTransactionId){ const source=data.transactions.find(t=>t.id===goal.sourceTransactionId); return source?Math.max(0,netOf(data.transactions.filter(t=>t.createdAt>source.createdAt))):0; } return Math.max(0,(Number(goal.initialAmount)||0)+netOf(related)); }
function renderGoals(){ const container=$('goalList'); const goals=[...data.goals].sort((a,b)=>(priorityOrder[a.priority]??2)-(priorityOrder[b.priority]??2)||String(a.deadline).localeCompare(String(b.deadline))); container.innerHTML=goals.map(goal=>{ const progress=goalProgress(goal); const spent=goal.spentTransactionId; const status=spent?'支出済み':goal.type==='restore'?'回復中':'積立中'; return `<article class="goal-item"><div><strong>${escapeHtml(goal.name)}</strong><button class="priority-button" data-goal-id="${goal.id}">優先度：${priorityLabels[goal.priority]||'通常'} ▾</button></div><span>${status}${goal.deadline?` · ${goal.deadline.replaceAll('-','/')}まで`:''}</span><b>${yen(Math.min(goal.target,progress))} <small>/ ${yen(goal.target)}</small></b><div class="progress-track"><i style="width:${Math.min(100,progress/goal.target*100)}%"></i></div></article>`; }).join(''); $('goalEmpty').hidden=data.goals.length>0; }
function assetStats(){ const a=data.assets||{}; if(!a.total||!a.asOf||!a.startDate) return null; const historical=data.transactions.filter(t=>t.date>=a.startDate&&t.date<=a.asOf); const future=data.transactions.filter(t=>t.date>a.asOf); const change=netOf(historical); return {current:Number(a.total)+netOf(future),opening:Number(a.total)-change,change,a}; }
function renderAssets(){ const stats=assetStats(); const reserved=data.goals.filter(g=>g.type==='save'&&!g.spentTransactionId).reduce((sum,g)=>sum+Math.min(g.target,goalProgress(g)),0); $('assetCurrentValue').textContent=stats?yen(stats.current):'未設定'; $('assetCurrentNote').textContent=stats?`${stats.a.asOf.replaceAll('-','/')}時点の実残高を基準にしています`:'最初に現在の資産を入力してください'; $('assetOpeningValue').textContent=stats?yen(stats.opening):'—'; $('assetOpeningNote').textContent=stats?`${stats.a.startDate.replaceAll('-','/')}時点（自動計算）`:'開始日を設定すると計算されます'; $('assetChangeValue').textContent=stats?`${stats.change>=0?'+':''}${yen(stats.change)}`:'—'; $('assetChangeNote').textContent=stats?'開始日から基準日までの収入 − 支出':'収入 − 支出'; $('assetReservedValue').textContent=stats?yen(reserved):'—'; $('assetAvailableValue').textContent=stats?yen(stats.current-reserved):'—'; }
function renderAnalysis(){ const month=currentMonth(); const sums={}; data.transactions.filter(t=>t.type==='expense'&&t.date.startsWith(month)).forEach(t=>sums[t.category]=(sums[t.category]||0)+t.amount); const entries=Object.entries(sums).sort((a,b)=>b[1]-a[1]); $('categoryAnalysis').innerHTML=entries.length?entries.map(([name,amount])=>`<article><span>${iconFor(name)} ${escapeHtml(name)}</span><b>${yen(amount)}</b></article>`).join(''):'<p class="goal-note">この月の支出を入力すると、カテゴリ別に表示されます。</p>'; }
function setView(view){ document.body.dataset.view=view; $('analysisView').hidden=view!=='analysis'; $('assetsView').hidden=view!=='assets'; document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); $('addTransaction').hidden=view!=='household'; }

function render(){
  const month=currentMonth(); $('currentMonth').textContent=formatMonth(month);
  const list=data.transactions.filter(t=>t.date.startsWith(month));
  const income=list.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0);
  const expense=list.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0);
  $('monthlyIncome').textContent=yen(income); $('monthlyExpense').textContent=yen(expense); $('monthlyBalance').textContent=yen(income-expense);
  const budget=Number(data.budget)||0; $('budgetValue').textContent=budget?`${yen(expense)} / ${yen(budget)}`:'未設定'; $('budgetNote').textContent=budget?(budget-expense>=0?`残り ${yen(budget-expense)}`:`${yen(expense-budget)} オーバー`):'支出の上限を決めましょう';
  const stats=assetStats(); $('assetValue').textContent=stats?yen(stats.current):'未入力'; $('assetNote').textContent=stats?`${stats.a.asOf.replaceAll('-','/')} 時点`:'収支とは別に管理します'; renderAssets(); renderAnalysis();
  const expenses=list.filter(t=>t.type==='expense'); const totalByCategory={}; expenses.forEach(t=>totalByCategory[t.category]=(totalByCategory[t.category]||0)+t.amount);
  const top=Object.entries(totalByCategory).sort((a,b)=>b[1]-a[1])[0]; $('topCategory').textContent=top?.[0]||'—'; $('topCategoryAmount').textContent=yen(top?.[1]||0); $('transactionCount').textContent=`${list.length}件`;
  renderGoals();
  const visible=filter==='all'?list:list.filter(t=>t.type===filter); const container=$('transactionList'); container.innerHTML=visible.sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt).map(t=>`<article class="transaction" data-id="${t.id}"><span class="category-icon">${iconFor(t.category)}</span><div class="transaction-info"><strong>${escapeHtml(t.memo)||t.category}</strong><span>${t.category} · ${new Date(t.date+'T00:00:00').toLocaleDateString('ja-JP',{month:'numeric',day:'numeric'})}</span></div><span class="transaction-amount ${t.type}">${t.type==='income'?'+':'−'}${yen(t.amount)}</span></article>`).join('');
  $('emptyState').hidden=visible.length>0; $('filterButton').textContent=(filter==='all'?'すべて':filter==='income'?'収入':'支出')+' ▾';
}
function escapeHtml(str=''){ return str.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function openTransaction(transaction){ const editing=!!transaction; $('transactionDialogTitle').textContent=editing?'明細を編集':'明細を追加'; $('transactionId').value=transaction?.id||''; selectedType=transaction?.type||'expense'; $('amount').value=transaction?.amount||''; $('transactionDate').value=transaction?.date||dateValue(); $('memo').value=transaction?.memo||''; $('newCategoryName').value=''; $('goalLink').innerHTML='<option value="">目標に紐付けない</option>'+data.goals.filter(g=>g.type==='save'&&!g.spentTransactionId).map(g=>`<option value="${g.id}" ${g.id===transaction?.goalId?'selected':''}>${escapeHtml(g.name)}</option>`).join(''); setType(selectedType,transaction?.category); $('deleteTransaction').hidden=!editing; $('transactionDialog').showModal(); }
function setType(type, selectedCategory){ selectedType=type; document.querySelectorAll('.type-switch button').forEach(b=>b.classList.toggle('selected',b.dataset.type===type)); categoryOptions(type,selectedCategory); }
function toggleNewCategory(){ const adding=$('category').value==='__new__'; $('newCategoryRow').hidden=!adding; $('newCategoryName').required=adding; if(adding) $('newCategoryName').focus(); }

$('addTransaction').onclick=()=>openTransaction();
document.querySelectorAll('.type-switch button').forEach(b=>b.onclick=()=>setType(b.dataset.type));
$('category').onchange=toggleNewCategory;
$('transactionForm').addEventListener('submit',e=>{ e.preventDefault(); const amount=Number($('amount').value); if(!amount) return; const id=$('transactionId').value; let category=$('category').value; if(category==='__new__'){ category=$('newCategoryName').value.trim(); if(!category) return $('newCategoryName').focus(); if(!allCategories(selectedType).includes(category)) data.categories[selectedType].push(category); } const tx={id:id||crypto.randomUUID(),type:selectedType,amount,category,date:$('transactionDate').value,memo:$('memo').value.trim(),goalId:$('goalLink').value||null,createdAt:id?data.transactions.find(t=>t.id===id).createdAt:Date.now()}; const goal=data.goals.find(g=>g.id===tx.goalId); const progressBefore=goal?goalProgress(goal):0; if(id) data.transactions=data.transactions.map(t=>t.id===id?tx:t); else data.transactions.push(tx); if(goal?.type==='save'&&tx.type==='expense'&&!goal.spentTransactionId){ const shortfall=Math.max(0,tx.amount-progressBefore); goal.spentTransactionId=tx.id; if(shortfall&&!data.goals.some(g=>g.sourceTransactionId===tx.id)) data.goals.push({id:crypto.randomUUID(),type:'restore',name:`${goal.name}の不足分を回復`,target:shortfall,initialAmount:0,priority:goal.priority,startDate:tx.date,deadline:goal.deadline||'',sourceTransactionId:tx.id}); } persist(); $('transactionDialog').close(); render(); });
$('deleteTransaction').onclick=()=>{ const id=$('transactionId').value; if(confirm('この明細を削除しますか？')){data.transactions=data.transactions.filter(t=>t.id!==id);persist();$('transactionDialog').close();render();} };
$('transactionList').onclick=e=>{ const row=e.target.closest('.transaction'); if(row) openTransaction(data.transactions.find(t=>t.id===row.dataset.id)); };
$('previousMonth').onclick=()=>changeMonth(-1); $('nextMonth').onclick=()=>changeMonth(1); $('monthPicker').onclick=()=>$('monthInput').showPicker?.() || $('monthInput').click(); $('monthInput').onchange=render;
function changeMonth(amount){ const [y,m]=currentMonth().split('-').map(Number); $('monthInput').value=`${new Date(y,m-1+amount,1).getFullYear()}-${String(new Date(y,m-1+amount,1).getMonth()+1).padStart(2,'0')}`;render(); }
$('filterButton').onclick=()=>{filter=filter==='all'?'expense':filter==='expense'?'income':'all';render();};
$('addGoal').onclick=()=>{$('goalTypeInput').value='save';$('goalNameInput').value='';$('goalTargetInput').value='';$('goalInitialInput').value='';$('goalPriorityInput').value='normal';$('goalStartInput').value=dateValue();$('goalDeadlineInput').value='';$('goalDialog').showModal();};
$('goalForm').addEventListener('submit',e=>{e.preventDefault();data.goals.push({id:crypto.randomUUID(),type:$('goalTypeInput').value,name:$('goalNameInput').value.trim()||'新しい目標',target:Number($('goalTargetInput').value),initialAmount:Number($('goalInitialInput').value)||0,priority:$('goalPriorityInput').value,startDate:$('goalStartInput').value,deadline:$('goalDeadlineInput').value});persist();$('goalDialog').close();render();});
$('goalList').onclick=e=>{const button=e.target.closest('.priority-button');if(!button)return;const goal=data.goals.find(g=>g.id===button.dataset.goalId);const cycle=['highest','high','normal','low'];goal.priority=cycle[(cycle.indexOf(goal.priority)+1)%cycle.length];persist();render();};
$('editBudget').onclick=$('editAssets').onclick=$('setupAssets').onclick=()=>{$('monthlyBudgetInput').value=data.budget||'';$('assetTotalInput').value=data.assets?.total||'';$('assetAsOfInput').value=data.assets?.asOf||dateValue();$('assetStartInput').value=data.assets?.startDate||`${currentMonth()}-01`;$('moneyDialog').showModal();};
$('moneyForm').addEventListener('submit',e=>{e.preventDefault();data.budget=Number($('monthlyBudgetInput').value)||0;data.assets={total:Number($('assetTotalInput').value)||0,asOf:$('assetAsOfInput').value,startDate:$('assetStartInput').value};persist();$('moneyDialog').close();render();});
$('settingsButton').onclick=()=>$('settingsDialog').showModal();
$('exportButton').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`家計簿バックアップ-${dateValue()}.json`;a.click();URL.revokeObjectURL(a.href);};
$('importInput').onchange=e=>{const reader=new FileReader();reader.onload=()=>{try{const backup=JSON.parse(reader.result);if(!Array.isArray(backup.transactions))throw Error();data={...backup,goals:Array.isArray(backup.goals)?backup.goals:[],categories:backup.categories||{expense:[],income:[]},assets:{total:0,asOf:'',recordedAt:0,...backup.assets}};persist();$('settingsDialog').close();render();alert('バックアップを復元しました。');}catch{alert('有効なバックアップファイルではありません。');}};if(e.target.files[0])reader.readAsText(e.target.files[0]);};
$('clearData').onclick=()=>{if(confirm('すべての明細と貯金目標を削除しますか？この操作は元に戻せません。')){data={transactions:[],goal:{name:'貯金目標',target:0,saved:0}};persist();$('settingsDialog').close();render();}};
$('clearData').onclick=()=>{if(confirm('すべての明細・目標・設定を削除しますか？この操作は元に戻せません。')){data={transactions:[],goals:[],goal:{name:'貯金目標',target:0,saved:0,deadline:''},budget:0,assets:{total:0,asOf:'',recordedAt:0},categories:{expense:[],income:[]}};persist();$('settingsDialog').close();render();}};
$('analyticsButton')?.addEventListener('click',()=>setView('analysis'));
document.querySelectorAll('.bottom-nav button').forEach(button=>button.onclick=()=>setView(button.dataset.view));
$('monthInput').value=monthValue(); render(); if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
